FROM node:18 as build
WORKDIR /app
COPY ./ui/package.json .
RUN npm install
COPY ./ui/ .
COPY ./_shared/ /app/src/_shared
RUN npm run build

FROM nginx:1.21.0-alpine
COPY ./ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]