version: "3"

services:
  api:
    build:
      context: ./services
      dockerfile: ./api/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/api/src/:/app/src
      - ./services/_shared/:/app/_shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AUTH_TOKEN=${AUTH_TOKEN}
    command: npm run dev

  ui:
    build:
      context: ./services
      dockerfile: ./ui/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./services/ui/src/App/:/app/src/App
      - ./services/ui/src/config/:/app/src/config
      - ./services/ui/src/index.tsx:/app/src/index.tsx
      - /app/node_modules
