version: "3"

services:
  node-app:
    build:
      context: ./services
      dockerfile: ./node-app/Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start

  campaign-engine:
    build:
      context: ./services
      dockerfile: ./campaign-engine/Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start

  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile.prod
    ports:
      - "3001:80"
