version: "3"

services:
  node-app:
    build:
      context: ./services
      dockerfile: ./node-app/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/node-app/src/:/app/src
      - ./services/_shared/:/app/_shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  campaign-engine:
    build:
      context: ./services
      dockerfile: ./campaign-engine/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/campaign-engine/src/:/app/src
      - ./services/_shared/:/app/_shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  download-engine:
    build:
      context: ./services
      dockerfile: ./download-engine/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/download-engine/src/:/app/src
      - ./services/_shared/:/app/_shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  apply-filters-engine:
    build:
      context: ./services
      dockerfile: ./apply-filters-engine/Dockerfile
      args:
        NODE_ENV: development
    volumes:
      - ./services/apply-filters-engine/src/:/app/src
      - ./services/_shared/:/app/_shared
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./services/ui/:/app
      - /app/node_modules
