version: "3"

services:
  node-app:
    build:
      context: ./services/node-app
      args:
        NODE_ENV: development
    volumes:
      - ./services/node-app/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  ui:
    build:
      context: ./services/ui
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./services/ui/:/app
      - /app/node_modules
